<?php
declare(strict_types=1);session_start();
if(empty($_SESSION['user_id'])){header('Location: login.php');exit;}
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dashboard — OTPGenerator</title><style>
body{margin:0;background:#f6f7fb;font-family:system-ui;color:#151827}header{height:64px;background:#fff;border-bottom:1px solid #e6e7ef;display:flex;align-items:center;justify-content:space-between;padding:0 5%}.wrap{max-width:1120px;margin:auto;padding:30px 20px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card{background:#fff;border:1px solid #e5e6ee;border-radius:16px;padding:22px}.big{font-size:30px;font-weight:800}button,.btn{background:#6d35e8;color:#fff;border:0;border-radius:9px;padding:11px 15px;text-decoration:none;font-weight:700;cursor:pointer}.secondary{background:#eeeef5;color:#222}input{padding:11px;border:1px solid #ddd;border-radius:8px;width:100%;box-sizing:border-box;margin:6px 0 12px}@media(max-width:700px){.cards{grid-template-columns:1fr}}
</style></head><body><header><b>OTP<span style="color:#6d35e8">Generator</span></b><a class="btn secondary" href="logout.php">Logout</a></header><main class="wrap"><h1>Dashboard</h1><p>Welcome to your verification hub.</p><div class="cards"><div class="card"><div class="big" id="apps">—</div><div>Connected Apps</div></div><div class="card"><div class="big" id="pending">—</div><div>Pending Verifications</div></div><div class="card"><div class="big" id="verified">—</div><div>Verified Today</div></div></div><div class="card" style="margin-top:20px"><h2>Register an App</h2><form id="appForm"><input name="name" placeholder="App / Business name" required><input name="website_url" placeholder="Website URL"><button>Create App</button></form><pre id="result" style="white-space:pre-wrap"></pre></div><div class="card" style="margin-top:20px"><h2>API Test Console</h2><p>Use this later to create a QuiGo/Adizzle test verification without leaving the dashboard.</p><a class="btn" href="verify-test.php">Open Verification Test</a></div></main><script>
async function load(){let r=await fetch('index.php?route=stats');let j=await r.json();if(j.success){apps.textContent=j.apps;pending.textContent=j.pending;verified.textContent=j.verified}}
appForm.onsubmit=async e=>{e.preventDefault();let r=await fetch('index.php?route=create-app',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(appForm)))});let j=await r.json();result.textContent=JSON.stringify(j,null,2);if(j.success)load()};load();
</script></body></html>
